checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "checkpoints/${project_name}/${run_name}"
  monitor: "val/loss"
  mode: "min"
  save_top_k: 1
  
utils:
  _target_: src.callbacks.RichHyperparametersSummary
  title: "Hyperparameters"
