project_name: "meca-gate-attention"
run_name: "test"

defaults:
  - data : ames_housing
  - logger : wandb
  - callbacks: default
  - trainer : default
  - tokenizer : FeatureTokenizer
  - model: FTT_system      
  - _self_

seed_everything: 0

ckpt_path: null