project_name: "ft-transformer-gate-residuals"
run_name: "best_model"

defaults:
  - data : california_housing
  - logger : tensorboard
  - callbacks: swa
  - trainer : default
  - tokenizer : PLE
  - model: regression      
  - _self_

seed_everything: 4

ckpt_path: null

do_fit : true
do_test : true